### ISSUE TITLE
Interpolation does not work for expressions

### ISSUE THREAD

**Issue by fizruk** [nikita-volkov/neat-interpolation#20]
Somewhat surprisingly, interpolation only works for variables, not expressions:

```
>>> import qualified Data.Text as Text
>>> n = 123 :: Int
>>> s = Text.pack (show n)
>>> [text| ${s} |]
"123\n"
>>> [text| ${Text.pack (show n)} |]
"${Text.pack (show n)}\n"
```

**Comment by neongreen** [comment]
This is because otherwise neat-interpolation would have to include a
Haskell parser. There's no non-hacky way (AFAIK) to ask GHC to parse and
execute some substring of a quasiquote at compile time.

There are other libraries though that use haskell-src-meta for that, but
I'm actually glad that neat-interpolation doesn't – haskell-src-meta takes
too much time and memory to compile.

It's also possible to implement a small parser for a subset of Haskell
though and use that. Yesod went that way for its templating language, and
Nikita's own record library also used to do that.

**Comment by fizruk** [comment]
Thank you for the explanation! Perhaps it should be added to the documentation :)

I have switched to [`interpolate`](http://hackage.haskell.org/package/interpolate) for now, although it too does not fully meet my needs.
